### ISSUE TITLE
[1.20.1] Game wont boot with souls 1.0.6

### ISSUE THREAD

**Issue by Xplodin** [InnovativeOnlineIndustries/Industrial-Foregoing-Souls#4]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:**
???? 
**Titanium Version:**
3.8.25
**Crashlog If Applicable (Upload to pastebin/gist):**
Specific part:
```
Failed to create mod instance. ModID: industrialforegoingsouls, class com.buuz135.industrialforegoingsouls.IndustrialForegoingSouls
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Integer (java.lang.Double and java.lang.Integer are in module java.base of loader 'bootstrap')
	at com.hrznstudio.titanium.config.AnnotationConfigManager.scanClass(AnnotationConfigManager.java:72) ~[titanium-1.20.1-3.8.25.jar%231332!/:3.8.25]
	at com.hrznstudio.titanium.config.AnnotationConfigManager.lambda$scanClass$2(AnnotationConfigManager.java:90) ~[titanium-1.20.1-3.8.25.jar%231332!/:3.8.25]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.hrznstudio.titanium.config.AnnotationConfigManager.scanClass(AnnotationConfigManager.java:90) ~[titanium-1.20.1-3.8.25.jar%231332!/:3.8.25]
	at com.hrznstudio.titanium.config.AnnotationConfigManager.add(AnnotationConfigManager.java:41) ~[titanium-1.20.1-3.8.25.jar%231332!/:3.8.25]
	at com.hrznstudio.titanium.module.ModuleController.addConfig(ModuleController.java:64) ~[titanium-1.20.1-3.8.25.jar%231332!/:3.8.25]
	at com.hrznstudio.titanium.module.ModuleController.lambda$onPostInit$2(ModuleController.java:89) ~[titanium-1.20.1-3.8.25.jar%231332!/:3.8.25]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.hrznstudio.titanium.module.ModuleController.onPostInit(ModuleController.java:87) ~[titanium-1.20.1-3.8.25.jar%231332!/:3.8.25]
	at com.hrznstudio.titanium.module.ModuleController.<init>(ModuleController.java:57) ~[titanium-1.20.1-3.8.25.jar%231332!/:3.8.25]
	at com.buuz135.industrialforegoingsouls.IndustrialForegoingSouls.<init>(IndustrialForegoingSouls.java:46) ~[industrial-foregoing-souls-1.20.1-1.0.6.jar%231043!/:1.20.1-1.0.6]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.19.jar%231376!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.19.jar%231375!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

full log (by the way the mod worked fine before updating souls, once updated, it broke)
https://gist.github.com/Xplodin/7190ba2072b171b9e18436d3ad77a603

**Comment by Buuz135** [comment]
Can you try resetting the config file?
